### ISSUE TITLE
Gcal2 Question

### ISSUE THREAD

**Issue by djmtype** [cfjedimaster/eleventy-demos#2]
Hey @cfjedimaster I can't seem to get my pipeline endpoint to return my events. My Pipeline is connected to my calendar. I can see the events I just created in G-Cal within Pipedream. It's also successful at triggering new builds via my Netlify webhook when I use your Pipedream endpoint. 

The `PD_EVENTS` variable you're referring to is the calendar endpoint, correct? Mine is https://9b34c42d702a8c20980e67a84c25d75b.m.pipedream.net

At this endpoint, I see the default message: "Success! To customize this response, check out our docs here" instead of my calendar's JSON response. 

Yet, I added that node.js step to my workflow: 
```
$respond({
  status:200,
  body:steps.get_all_future_events.$return_value.items
});
```

I'm clearly missing something…
Even when I try to run 11ty locally, I'm getting this error: 
```
invalid json response body at https://pipedream.com/@me/personal-cal-p_mkCkpGD reason: Unexpected token < in JSON at position 0

`FetchError` was thrown:
    FetchError: invalid json response body at https://pipedream.com/@me/personal-cal-p_mkCkpGD reason: Unexpected token < in JSON at position 0
        at /Users/me/Sites/eleventy-events/node_modules/node-fetch/lib/index.js:272:32
        at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by djmtype** [comment]
With fresh eyes, I have the calendar Pipedream workflow working. Although it's throwing a mapping error on build, stating `TypeError: res.map is not a function`. Running `console.log(res[1])` shows `undefined`?

**Comment by djmtype** [comment]
With fresh eyes, I figured it out!

**Comment by cfjedimaster** [comment]
I've not been around, but I'm glad you got it!
