### ISSUE TITLE
Could you convert this into .njk or nunjucks?

### ISSUE THREAD

**Issue by talmax1124** [cfjedimaster/eleventy-demos#3]
Assign tag is not a thing in nunjucks. If this could be in .njk, it will be appreciated. Thank you!

**Comment by cfjedimaster** [comment]
Try set perhaps? 

https://mozilla.github.io/nunjucks/templating.html#set

**Comment by talmax1124** [comment]
It's giving me an error that it can't find /authors/johndoe/

**Comment by talmax1124** [comment]
or do you think when you have time you could do a Pull Request to this repo: https://github.com/talmax1124/knighttimesnews-restore @cfjedimaster

**Comment by cfjedimaster** [comment]
Can you please log a new bug?

**Comment by talmax1124** [comment]
You mean create a new issue?

**Comment by cfjedimaster** [comment]
Yes please.

**Comment by cfjedimaster** [comment]
Closing as there's been no progress on this.
